version: "3"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=profilebuilderfinal
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pb321
  web:
    build: .
    command: python practice/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/Profile-Builder
    ports:
      - "8000:8000"
    depends_on:
      - db
