# Generated by Django 3.0.5 on 2021-06-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(default='admin1')),
                ('mailid', models.TextField()),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('un_st', models.TextField(default='un', verbose_name='User name')),
                ('research_interest', models.TextField(default='cs', verbose_name='Research interest')),
            ],
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_of_faculty', models.IntegerField(default=0, verbose_name='ID')),
                ('areas_of_interests', models.TextField(default='computer science', verbose_name='aoi')),
                ('research', models.TextField(verbose_name='Research')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='images/view.jpg', upload_to='images/')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('mailid', models.TextField()),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('security_qn', models.CharField(default='question', max_length=100)),
                ('security_an', models.CharField(default='answer', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='images/view.jpg', upload_to='images/')),
                ('id_of_faculty', models.IntegerField(default=0, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('mailid', models.TextField()),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('security_qn', models.CharField(default='question', max_length=100)),
                ('security_an', models.CharField(default='answer', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers_areas_of_interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_of_faculty', models.IntegerField(default=0, verbose_name='ID')),
                ('name_of_faculty', models.TextField(verbose_name='Name of faculty')),
                ('faculty_research_interest', models.TextField(verbose_name='Faculty research interest')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_faculty', models.TextField(verbose_name='Name of faculty')),
                ('bio_of_faculty', models.TextField(verbose_name='Bio of faculty')),
                ('mail_of_faculty', models.TextField(verbose_name='Mail of faculty')),
                ('position', models.TextField(verbose_name='Position')),
                ('department', models.TextField(verbose_name='Department')),
                ('location', models.TextField(verbose_name='Location')),
            ],
        ),
    ]
