# Generated by Django 3.0.5 on 2021-04-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_builder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='teachers_areas_of_interest',
            name='id_of_faculty',
            field=models.IntegerField(default=0, verbose_name='ID'),
        ),
    ]
