# Generated by Django 3.0.5 on 2021-03-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='semester',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
