# Generated by Django 3.0.5 on 2021-04-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_builder', '0002_auto_20210423_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_of_student', models.IntegerField(default=0, verbose_name='ID')),
                ('student_research_interest', models.TextField(verbose_name='Research interest')),
            ],
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_of_faculty', models.IntegerField(default=0, verbose_name='ID')),
                ('research', models.TextField(verbose_name='Research')),
                ('title', models.TextField(verbose_name='Title')),
            ],
        ),
        migrations.AddField(
            model_name='teachers_data',
            name='id_of_faculty',
            field=models.IntegerField(default=0, verbose_name='ID'),
        ),
    ]
