# Generated by Django 3.0.5 on 2021-03-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_builder', '0003_auto_20210302_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('mailid', models.TextField()),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
