# Generated by Django 3.0.5 on 2021-04-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_builder', '0003_auto_20210425_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers_data',
            name='id_of_faculty',
        ),
        migrations.AddField(
            model_name='teachers',
            name='id_of_faculty',
            field=models.IntegerField(default=0, verbose_name='ID'),
        ),
    ]
