# Generated by Django 3.0.5 on 2021-03-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_builder', '0004_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers_scrapped_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_faculty', models.TextField()),
                ('position_of_faculty', models.TextField()),
                ('bio_of_faculty', models.TextField()),
                ('mail_of_faculty', models.TextField()),
                ('faculty_research_interest', models.TextField()),
            ],
        ),
    ]
