# Generated by Django 3.0.5 on 2021-05-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_builder', '0004_auto_20210425_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailid', models.TextField()),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
