# Generated by Django 3.0.5 on 2021-03-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_builder', '0005_teachers_scrapped_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers_areas_of_interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_faculty', models.TextField()),
                ('faculty_research_interest', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Teachers_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_faculty', models.TextField()),
                ('bio_of_faculty', models.TextField()),
                ('mail_of_faculty', models.TextField()),
                ('position', models.TextField()),
                ('department', models.TextField()),
                ('location', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Teachers_scrapped_data',
        ),
        migrations.AddField(
            model_name='students',
            name='security_an',
            field=models.CharField(default='answer', max_length=100),
        ),
        migrations.AddField(
            model_name='students',
            name='security_qn',
            field=models.CharField(default='question', max_length=100),
        ),
        migrations.AddField(
            model_name='teachers',
            name='security_an',
            field=models.CharField(default='answer', max_length=100),
        ),
        migrations.AddField(
            model_name='teachers',
            name='security_qn',
            field=models.CharField(default='question', max_length=100),
        ),
    ]
