# Generated by Django 3.0.5 on 2021-05-02 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_builder', '0005_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='admin_data',
        ),
    ]
