# Generated by Django 3.0.5 on 2021-04-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_builder', '0006_auto_20210329_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers_areas_of_interest',
            name='faculty_research_interest',
            field=models.TextField(verbose_name='Faculty research interest'),
        ),
        migrations.AlterField(
            model_name='teachers_areas_of_interest',
            name='name_of_faculty',
            field=models.TextField(verbose_name='Name of faculty'),
        ),
        migrations.AlterField(
            model_name='teachers_data',
            name='bio_of_faculty',
            field=models.TextField(verbose_name='Bio of faculty'),
        ),
        migrations.AlterField(
            model_name='teachers_data',
            name='department',
            field=models.TextField(verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='teachers_data',
            name='location',
            field=models.TextField(verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='teachers_data',
            name='mail_of_faculty',
            field=models.TextField(verbose_name='Mail of faculty'),
        ),
        migrations.AlterField(
            model_name='teachers_data',
            name='name_of_faculty',
            field=models.TextField(verbose_name='Name of faculty'),
        ),
        migrations.AlterField(
            model_name='teachers_data',
            name='position',
            field=models.TextField(verbose_name='Position'),
        ),
    ]
