# Generated by Django 3.0.5 on 2021-06-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_builder', '0007_admin_data_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='img',
            field=models.ImageField(default='images/view.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='img',
            field=models.ImageField(default='images/view.jpg', upload_to='images/'),
        ),
    ]
