# Generated by Django 3.0.5 on 2021-06-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_builder', '0009_remove_projects_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('un_st', models.TextField()),
                ('research_interest', models.TextField()),
            ],
        ),
    ]
