from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait
PATH="C:\Program Files (x86)\chromedriver.exe"
driver=webdriver.Chrome(PATH)
driver.maximize_window()
driver.get("http://127.0.0.1:8000/html/login")
uname=driver.find_elements_by_name("email")
uname[0].send_keys("adityasai0916@gmail.com")
pwd=driver.find_elements_by_name("password")
pwd[0].send_keys("SEproject1")
link=driver.find_elements_by_class_name("login_button")
print("clicked on login")
link[0].click()
print("login successful")
dropdown=driver.find_element_by_class_name("dropbtn")
print("found dropdown button")
dropdown.click()
print("dropdown opened successfully")
toggle=driver.find_element_by_xpath("//a[@href='/html/myProfile']")
toggle.click()
time.sleep(2)
toggle=driver.find_element_by_xpath("//a[@href='/html/editProfile']")
toggle.click()
time.sleep(2)
final=driver.find_element_by_xpath("//div[@class='overlay'][@onclick='changeMail_redirect()']")
final.click()
time.sleep(2)
email=driver.find_element_by_id("email")
email.send_keys("adityasai0916@gmail.com")
time.sleep(2)
submit=driver.find_element_by_xpath("//div[@class='PR_button']")
submit.click()
time.sleep(2)
driver.quit()
